package csc545project;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
import java.*;

/**
 *
 * @author CassieAlyce
 */
public class addIngredientGUI extends javax.swing.JFrame {

    /**
     * Creates new form addIngredientGUI
     */
    GUI parentWindow;
    public addIngredientGUI(GUI pWindow) {
        initComponents();
        Ingredient myIngredient = new Ingredient();
        foodGroupCB.setModel(myIngredient.getFoodGroups());
        parentWindow = pWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        ingredientTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        quantityTextF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        foodGroupCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        caloriesTF = new javax.swing.JTextField();
        sugarTextF = new javax.swing.JTextField();
        sodiumTF = new javax.swing.JTextField();
        fatTextF = new javax.swing.JTextField();
        proteinTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(392, 437));
        setPreferredSize(new java.awt.Dimension(392, 437));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(150, 350, 122, 23);

        ingredientTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ingredientTF.setMinimumSize(new java.awt.Dimension(20, 19));
        ingredientTF.setPreferredSize(new java.awt.Dimension(20, 25));
        ingredientTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientTFActionPerformed(evt);
            }
        });
        getContentPane().add(ingredientTF);
        ingredientTF.setBounds(150, 10, 172, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingredient Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 18, 118, 17);

        quantityTextF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantityTextF.setMinimumSize(new java.awt.Dimension(12, 20));
        quantityTextF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(quantityTextF);
        quantityTextF.setBounds(150, 50, 59, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(109, 101, 0, 0);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Food Group");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 82, 17);

        foodGroupCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(foodGroupCB);
        foodGroupCB.setBounds(150, 90, 148, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calories");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 54, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sugar(g)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 70, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sodium (g)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fat (g)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 60, 17);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Protein (g)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 80, 17);

        caloriesTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caloriesTF.setMinimumSize(new java.awt.Dimension(12, 20));
        caloriesTF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(caloriesTF);
        caloriesTF.setBounds(150, 120, 59, 30);

        sugarTextF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sugarTextF.setMinimumSize(new java.awt.Dimension(12, 20));
        sugarTextF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(sugarTextF);
        sugarTextF.setBounds(150, 160, 59, 30);

        sodiumTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sodiumTF.setMinimumSize(new java.awt.Dimension(12, 20));
        sodiumTF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(sodiumTF);
        sodiumTF.setBounds(150, 280, 59, 30);

        fatTextF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fatTextF.setMinimumSize(new java.awt.Dimension(12, 20));
        fatTextF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(fatTextF);
        fatTextF.setBounds(150, 200, 59, 30);

        proteinTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proteinTF.setMinimumSize(new java.awt.Dimension(12, 20));
        proteinTF.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(proteinTF);
        proteinTF.setBounds(150, 240, 59, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingredientTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientTFActionPerformed
        
    }//GEN-LAST:event_ingredientTFActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Ingredient newIngredient = new Ingredient();
        if (newIngredient.doesExist(ingredientTF.getText())) {
            JOptionPane.showMessageDialog(this, "Ingredient Already Exists.");
        } else {
                if (Integer.parseInt(caloriesTF.getText()) < 0
                        || Float.parseFloat(proteinTF.getText()) < 0
                        || Float.parseFloat(sugarTextF.getText()) < 0
                        || Float.parseFloat(fatTextF.getText()) < 0
                        || Float.parseFloat(sodiumTF.getText()) < 0
                        || Integer.parseInt(quantityTextF.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "All values must be greater than zero.");
                } else {
                    String fg = (String)foodGroupCB.getSelectedItem();
                   boolean result = newIngredient.addIngredient(ingredientTF.getText(), 
                    Integer.parseInt(caloriesTF.getText()), Float.parseFloat(proteinTF.getText()),
                   Float.parseFloat(sugarTextF.getText()), Float.parseFloat(fatTextF.getText()),
                   Float.parseFloat(sodiumTF.getText()), fg, 
                   Integer.parseInt(quantityTextF.getText()));
                   if(result){
                       JOptionPane.showMessageDialog(this, ""+ingredientTF.getText()+" was added successfully");
                       caloriesTF.setText("");
                       proteinTF.setText("");
                       sugarTextF.setText("");
                       fatTextF.setText("");
                       sodiumTF.setText("");
                       quantityTextF.setText("");
                       ingredientTF.setText("");
                       parentWindow.ingredientList.setModel(newIngredient.populateIngredientsDropDown());
                       parentWindow.initializeSearchTables();
                       parentWindow.initializeShoppingTab();
                   }
                   else{
                       JOptionPane.showMessageDialog(this, ""+ingredientTF.getText()+" could not be added.");
                   }
                }
        }
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addIngredientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addIngredientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addIngredientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addIngredientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caloriesTF;
    private javax.swing.JTextField fatTextF;
    private javax.swing.JComboBox foodGroupCB;
    private javax.swing.JTextField ingredientTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField proteinTF;
    private javax.swing.JTextField quantityTextF;
    private javax.swing.JTextField sodiumTF;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField sugarTextF;
    // End of variables declaration//GEN-END:variables
}
