package csc545project;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NewLaptop
 */
public class AddRecipeGUI extends javax.swing.JFrame {
    GUI parentWindow;
    /**
     * Creates new form AddRecipe
     */
    public AddRecipeGUI(GUI parent) {
        parentWindow = parent;
        initComponents();
        addCategoriesToTable();
        addIngredientsToTable();
    }
    public void addCategoriesToTable() {
        Category c = new Category();
        ArrayList<String> cat = new ArrayList<>();
        cat = c.allCategories();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (String temp : cat) {
            model.addRow(new Object[]{false,temp});
        }
    }
    public void addIngredientsToTable() {
        Ingredient ing = new Ingredient();
        ArrayList<String> i = new ArrayList<>();
        i = ing.getIngredientList();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (String temp : i) {
            model.addRow(new Object[]{false,temp,1});
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        recipeNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionsTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        addCatButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addRecButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(440, 610));
        setPreferredSize(new java.awt.Dimension(440, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recipe Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 14, 100, 17);

        recipeNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(recipeNameTF);
        recipeNameTF.setBounds(114, 11, 300, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Instructions:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 57, 90, 17);

        instructionsTA.setColumns(20);
        instructionsTA.setRows(5);
        jScrollPane1.setViewportView(instructionsTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(114, 55, 300, 160);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categories:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(35, 390, 79, 17);

        addCatButton.setText("Add Category");
        addCatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addCatButton);
        addCatButton.setBounds(0, 420, 110, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(115, 391, 299, 142);

        addRecButton.setText("Add Recipe");
        addRecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addRecButton);
        addRecButton.setBounds(167, 539, 120, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingredients:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(28, 230, 86, 17);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Ingredient", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(2).setMinWidth(60);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(115, 225, 299, 155);

        jLabel5.setIcon(new javax.swing.ImageIcon("W:\\CSC545\\CSC545Project\\src\\csc545project\\addRecipe.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 424, 573);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void addCatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatButtonActionPerformed
        try {
        String cat = JOptionPane.showInputDialog(rootPane, "Please enter a category:", "Add Category", JOptionPane.PLAIN_MESSAGE);
            if(cat.charAt(0)==' ') {
                JOptionPane.showMessageDialog(null, "Not a valid entry.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Category cg = new Category();
                cg.addCategory(cat);
                JOptionPane.showMessageDialog(null, "Category Added Successfully", "Add Category", JOptionPane.PLAIN_MESSAGE);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{false,cat});
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_addCatButtonActionPerformed

    private void addRecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecButtonActionPerformed
        Recipes rec = new Recipes();
        String r = recipeNameTF.getText();
        if((!r.equals("")) && !rec.checkExistingRecipes(r)) {

            String i = instructionsTA.getText();
            ArrayList<Integer> n = new ArrayList<>();
            ArrayList<String> cat = new ArrayList<>();
            ArrayList<String> ing = new ArrayList<>();
            for (int j=0; j<jTable1.getRowCount(); j++) {
                if((Boolean)jTable1.getValueAt(j, 0))
                    cat.add(jTable1.getValueAt(j, 1).toString());
            }
            if(cat.size()>0) {
                for (int j=0; j<jTable2.getRowCount(); j++)
                    if((Boolean)jTable2.getValueAt(j, 0)) {
                        ing.add(jTable2.getValueAt(j, 1).toString());
                        n.add(Integer.parseInt(jTable2.getValueAt(j, 2).toString()));
                    }
                if(ing.size()>0) {
                    rec.addRecipes(r, i, n, cat, ing);
                    parentWindow.jList2.setModel(rec.getRecipeNames());
                    parentWindow.updateWMcb();
                    JOptionPane.showMessageDialog(null, "Recipe Added Successfully!", "Add Recipe", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Please select at least one ingredient.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null, "Please select at least one category.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
            if(r.equals(""))
                JOptionPane.showMessageDialog(null, "Please enter a recipe name.", "Error", JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Recipe already exist.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_addRecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecipeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCatButton;
    private javax.swing.JButton addRecButton;
    private javax.swing.JTextArea instructionsTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField recipeNameTF;
    // End of variables declaration//GEN-END:variables
}
