package csc545project;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thomas_wilson78
 */
public class GUI extends javax.swing.JFrame {
    Fridge theFridge; //class variable that represent's the user's fridge
    private GUI parentWindow;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        parentWindow = this;
        updateWMcb();
        theFridge = new Fridge();
        updateFridgeComponents();
        updateShoppingComponents();
        updateRecipeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void updateRecipeComponents(){
        Recipes myRecipe = new Recipes();
        jList2.setModel(myRecipe.getRecipeNames());
    }
    void updateShoppingComponents(){
        Ingredient nextIngr = new Ingredient();
        jComboBox2.setModel(nextIngr.populateIngredientsDropDown());
    }
    private void updateFridgeComponents(){
        ingredientList.setModel(theFridge.populateFridgeList());
    }
    private void clearFridgeIngredientFields() {
        itemTF.setText("");
        quantityTF.setText("");
        fgTF.setText("");
        calTF.setText("");
        fatTF.setText("");
        proTF1.setText("");
        sugarTF.setText("");
        sodTF.setText("");
    }
    @SuppressWarnings("unchecked")
    public void updateWMcb() {
        WMenu wm = new WMenu();
        ArrayList<String> allRecipe = new ArrayList<>();
        allRecipe = wm.allRecipes();
        mbcbox.setModel(new DefaultComboBoxModel(allRecipe.toArray()));
        mlcbox.setModel(new DefaultComboBoxModel(allRecipe.toArray()));
        mdcbox.setModel(new DefaultComboBoxModel(allRecipe.toArray()));
        loadMenuDayWM();
    }
    private void loadMenuDayWM() {
        WMenu wm = new WMenu();
        ArrayList<String> r = wm.changeDay(daycbox.getSelectedItem().toString());
        if (r.get(0)!=null)
            mbcbox.setSelectedItem(r.get(0));
        else
            mbcbox.setSelectedItem("-empty-");
        if (r.get(2)!=null)
            mlcbox.setSelectedItem(r.get(2));
        else
            mlcbox.setSelectedItem("-empty-");
        if (r.get(1)!=null)
            mdcbox.setSelectedItem(r.get(1));
        else
            mdcbox.setSelectedItem("-empty-");
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        addRecipeButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fgTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fatTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sodTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        proTF1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sugarTF = new javax.swing.JTextField();
        upQuanButton = new javax.swing.JButton();
        downQuanButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        daycbox = new javax.swing.JComboBox();
        mlcbox = new javax.swing.JComboBox();
        mdcbox = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        mbcbox = new javax.swing.JComboBox();
        updateDayButton = new javax.swing.JButton();
        wmClearButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        quanTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(680, 340));
        setPreferredSize(new java.awt.Dimension(680, 340));
        setResizable(false);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel3.setLayout(null);

        jList2.setBackground(new java.awt.Color(255, 255, 204));
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setMaximumSize(null);
        jList2.setMinimumSize(null);
        jList2.setPreferredSize(null);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 44, 143, 200);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("Recipes");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 19, 52, 17);
        jPanel3.add(jLabel41);
        jLabel41.setBounds(286, 44, 0, 0);

        jList4.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane5.setViewportView(jList4);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(171, 44, 111, 200);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 102));
        jLabel42.setText("Ingredients");
        jPanel3.add(jLabel42);
        jLabel42.setBounds(171, 21, 81, 17);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane6);
        jScrollPane6.setBounds(296, 44, 245, 200);

        jList5.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane7.setViewportView(jList5);

        jPanel3.add(jScrollPane7);
        jScrollPane7.setBounds(559, 44, 102, 200);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 102));
        jLabel43.setText("Instructions");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(308, 21, 85, 17);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 102));
        jLabel44.setText("Category");
        jPanel3.add(jLabel44);
        jLabel44.setBounds(573, 21, 64, 17);

        addRecipeButton.setText("Add Recipe");
        addRecipeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRecipeButtonMouseClicked(evt);
            }
        });
        addRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addRecipeButton);
        addRecipeButton.setBounds(270, 250, 110, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc545project/foodbackground.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 0, 680, 290);

        jTabbedPane2.addTab("Recipes", jPanel3);

        jPanel2.setLayout(null);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        ingredientList.setBackground(new java.awt.Color(255, 255, 204));
        ingredientList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ingredientList.setDragEnabled(true);
        ingredientList.setMaximumSize(null);
        ingredientList.setMinimumSize(null);
        ingredientList.setPreferredSize(null);
        ingredientList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ingredientListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ingredientList);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 39, 102, 202);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Items");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 19, 41, 17);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Item Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 20, 83, 17);

        itemTF.setEditable(false);
        itemTF.setBackground(new java.awt.Color(255, 255, 204));
        itemTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(itemTF);
        itemTF.setBounds(220, 20, 126, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Quantity:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(360, 25, 65, 17);

        quantityTF.setEditable(false);
        quantityTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(quantityTF);
        quantityTF.setBounds(430, 20, 35, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Food Group:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 60, 87, 17);

        fgTF.setEditable(false);
        fgTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(fgTF);
        fgTF.setBounds(220, 60, 126, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Calories:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(160, 100, 59, 17);

        calTF.setEditable(false);
        calTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(calTF);
        calTF.setBounds(220, 100, 126, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Fat:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(370, 105, 27, 17);

        fatTF.setEditable(false);
        fatTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(fatTF);
        fatTF.setBounds(400, 100, 35, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Protein:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(460, 105, 55, 17);

        sodTF.setEditable(false);
        sodTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(sodTF);
        sodTF.setBounds(220, 140, 35, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Sugar:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(350, 145, 46, 17);

        proTF1.setEditable(false);
        proTF1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(proTF1);
        proTF1.setBounds(520, 100, 35, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Sodium:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 145, 57, 17);

        sugarTF.setEditable(false);
        sugarTF.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(sugarTF);
        sugarTF.setBounds(400, 140, 35, 30);

        upQuanButton.setText("+");
        upQuanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upQuanButtonActionPerformed(evt);
            }
        });
        jPanel2.add(upQuanButton);
        upQuanButton.setBounds(470, 22, 41, 23);

        downQuanButton.setText("-");
        downQuanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downQuanButtonActionPerformed(evt);
            }
        });
        jPanel2.add(downQuanButton);
        downQuanButton.setBounds(520, 22, 37, 23);

        jToggleButton1.setText("All Ingredients");
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(10, 250, 140, 23);

        jButton1.setText("Add New Ingredient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(200, 250, 170, 23);

        jLabel12.setBackground(new java.awt.Color(255, 255, 204));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("W:\\CSC545\\CSC545Project\\src\\csc545project\\foodbackground.jpg")); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 680, 290);

        jTabbedPane2.addTab("Fridge", jPanel2);

        jPanel1.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 102));
        jLabel18.setText("Breakfast");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(180, 19, 66, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 102));
        jLabel19.setText("Lunch");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(180, 70, 42, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 102));
        jLabel20.setText("Dinner");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(180, 120, 45, 17);

        daycbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        daycbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daycboxActionPerformed(evt);
            }
        });
        jPanel1.add(daycbox);
        daycbox.setBounds(10, 40, 100, 20);

        jPanel1.add(mlcbox);
        mlcbox.setBounds(180, 90, 300, 20);

        jPanel1.add(mdcbox);
        mdcbox.setBounds(180, 140, 300, 20);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 102));
        jLabel45.setText("Day");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(10, 19, 26, 17);

        jPanel1.add(mbcbox);
        mbcbox.setBounds(180, 40, 300, 20);

        updateDayButton.setText("Update");
        updateDayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateDayButtonMouseClicked(evt);
            }
        });
        jPanel1.add(updateDayButton);
        updateDayButton.setBounds(10, 250, 90, 23);

        wmClearButton.setText("Clear Week");
        wmClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wmClearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wmClearButton);
        wmClearButton.setBounds(120, 250, 110, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon("W:\\CSC545\\CSC545Project\\src\\csc545project\\foodbackground.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 680, 290);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Weekly Menu", jPanel4);

        jPanel11.setLayout(null);

        jScrollPane3.setViewportView(jList3);

        jPanel11.add(jScrollPane3);
        jScrollPane3.setBounds(10, 34, 102, 242);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 102));
        jLabel39.setText("Ingredients");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(211, 11, 81, 17);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 102));
        jLabel40.setText("Catagories");
        jPanel11.add(jLabel40);
        jLabel40.setBounds(504, 11, 74, 17);

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        jPanel11.add(searchBTN);
        searchBTN.setBounds(130, 253, 90, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("Results");
        jPanel11.add(jLabel11);
        jLabel11.setBounds(32, 11, 50, 17);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel11.add(jScrollPane8);
        jScrollPane8.setBounds(415, 34, 250, 190);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(50);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel11.add(jScrollPane9);
        jScrollPane9.setBounds(130, 34, 250, 190);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc545project/foodbackground.jpg"))); // NOI18N
        jPanel11.add(jLabel15);
        jLabel15.setBounds(0, -6, 680, 300);

        jTabbedPane2.addTab("Search", jPanel11);

        jPanel6.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredients", "Quantity Needed"
            }
        ));
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(10, 11, 390, 265);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 102));
        jLabel47.setText("Add Ingredient To Fridge");
        jPanel6.add(jLabel47);
        jLabel47.setBounds(410, 30, 175, 17);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 102));
        jLabel48.setText("Quantity");
        jPanel6.add(jLabel48);
        jLabel48.setBounds(410, 80, 60, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox2);
        jComboBox2.setBounds(410, 50, 175, 20);
        jPanel6.add(quanTF);
        quanTF.setBounds(410, 110, 28, 30);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(440, 110, 80, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc545project/foodbackground.jpg"))); // NOI18N
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, -6, 680, 300);

        jTabbedPane2.addTab("Shopping List", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Fridge");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDayButtonMouseClicked
        WMenu wm = new WMenu();
        String day = daycbox.getSelectedItem().toString();
        String b = mbcbox.getSelectedItem().toString();
        String l = mlcbox.getSelectedItem().toString();
        String d = mdcbox.getSelectedItem().toString();
        if(wm.updateMenu(day, b, l, d)) {
            JOptionPane.showMessageDialog(null, "Update Successful!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Update Failed!");
        }
    }//GEN-LAST:event_updateDayButtonMouseClicked

    private void addRecipeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRecipeButtonMouseClicked
       
    }//GEN-LAST:event_addRecipeButtonMouseClicked

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ingredient newIngr = new Ingredient();
        String ingrName = (String)jComboBox2.getSelectedItem();
        newIngr.setIngredient(ingrName);
        newIngr.upIngredient(Integer.parseInt(quanTF.getText()));
        quanTF.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void daycboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daycboxActionPerformed
        loadMenuDayWM();
    }//GEN-LAST:event_daycboxActionPerformed

    private void wmClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wmClearButtonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to reset the weekly meal plan?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            WMenu wm = new WMenu();
            wm.resetWeeklyMenu();
            JOptionPane.showMessageDialog(null, "Meal plan reset successfully.");
            loadMenuDayWM();
        }
    }//GEN-LAST:event_wmClearButtonActionPerformed

    private void upQuanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upQuanButtonActionPerformed
        String ingrName = (String) ingredientList.getSelectedValue();
        Ingredient selectedIngredient = new Ingredient();
        if(!jToggleButton1.isSelected()){  
        selectedIngredient = theFridge.getIngredient(ingrName);
        if(selectedIngredient != null){
        theFridge.incrementFridgeIngredient(selectedIngredient);
        updateIngredientFields();
        }
        }
        else{
            selectedIngredient.setIngredient(ingrName);
            System.out.println(selectedIngredient.quantity);
            selectedIngredient.upIngredient(1);
            System.out.println(selectedIngredient.quantity);
            updateIngredientFields();
        }
        
    }//GEN-LAST:event_upQuanButtonActionPerformed

    private void downQuanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downQuanButtonActionPerformed
        String ingrName = (String) ingredientList.getSelectedValue();
        Ingredient selectedIngredient = new Ingredient();
        if(!jToggleButton1.isSelected()){ 
        selectedIngredient = theFridge.getIngredient(ingrName);
        if(selectedIngredient != null){
        theFridge.decrease(selectedIngredient);
        if(selectedIngredient.quantity>0){
        updateIngredientFields();      
        }
        else{
            clearFridgeIngredientFields();
            ingredientList.setModel(theFridge.populateFridgeList());
        }
        }// TODO add your handling code here:
        }
        else{
            selectedIngredient.setIngredient(ingrName);
            selectedIngredient.subtractIngredient(1);
            updateIngredientFields();
        }
    }//GEN-LAST:event_downQuanButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void ingredientListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ingredientListValueChanged
        updateIngredientFields();
    }//GEN-LAST:event_ingredientListValueChanged

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        ingredientList.setModel(theFridge.populateFridgeList());
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        if(jToggleButton1.isSelected()){
            ingredientList.setModel(theFridge.populateIngredientsList());
            jToggleButton1.setText("Fridge Ingredients");
        }
        else{
            ingredientList.setModel(theFridge.populateFridgeList());
            jToggleButton1.setText("All Ingredients");
        }
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void addRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtonActionPerformed
        new AddRecipeGUI(parentWindow).setVisible(true);
    }//GEN-LAST:event_addRecipeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new addIngredientGUI(parentWindow).setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        Recipes selectedRecipe = new Recipes();
        jList4.setModel(selectedRecipe.getRecipeIngredients((String)jList2.getSelectedValue()));
        jTextArea1.setText(selectedRecipe.getRecipesInstructions((String)jList2.getSelectedValue()));
        jList5.setModel(selectedRecipe.getRecipeCategory((String)jList2.getSelectedValue()));
    }//GEN-LAST:event_jList2ValueChanged
    private void updateIngredientFields(){
        String ingrName = (String) ingredientList.getSelectedValue();
        Ingredient selectedIngredient = new Ingredient();
        if(!jToggleButton1.isSelected()){
        selectedIngredient = theFridge.getIngredient(ingrName);

        }
        else{
        selectedIngredient.setIngredient(ingrName);    
        }

        itemTF.setText(selectedIngredient.ingredient_name);
        quantityTF.setText("" + selectedIngredient.quantity + "");
        fgTF.setText(selectedIngredient.food_group);
        calTF.setText("" + selectedIngredient.calories + "");
        fatTF.setText("" + selectedIngredient.fat + "");
        proTF1.setText("" + selectedIngredient.protein + "");
        sugarTF.setText("" + selectedIngredient.sugar + "");
        sodTF.setText("" + selectedIngredient.sodium + "");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeButton;
    private javax.swing.JTextField calTF;
    private javax.swing.JComboBox daycbox;
    private javax.swing.JButton downQuanButton;
    private javax.swing.JTextField fatTF;
    private javax.swing.JTextField fgTF;
    public javax.swing.JList ingredientList;
    private javax.swing.JTextField itemTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox mbcbox;
    private javax.swing.JComboBox mdcbox;
    private javax.swing.JComboBox mlcbox;
    private javax.swing.JTextField proTF1;
    private javax.swing.JTextField quanTF;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField sodTF;
    private javax.swing.JTextField sugarTF;
    private javax.swing.JButton upQuanButton;
    private javax.swing.JButton updateDayButton;
    private javax.swing.JButton wmClearButton;
    // End of variables declaration//GEN-END:variables
}
